# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -p:PublishSingleFile=true -p:IncludeContentInSingleFile=true -p:Configuration=Release --sc -p:PublishAot=false -p:PublishTrimmed=false -p:IncludeAllContentForSelfExtract=true -p:EnableCompressionInSingleFile=true 

    - name: Upload API(Publish,Single File)
      uses: actions/upload-artifact@v4
      with:
        name: RandomImageAPI
        path: ${{ github.workspace }}/bin/Release/net9.0/linux-x64/publish
        if-no-files-found: ignore
